server:
  port: 8081
spring:
  application:
    name: customer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak-bank:8080/realms/bank-realm
  datasource:
    url: jdbc:postgresql://postgres-bank:5432/customer
    username: ${PG_USER:-pguser}
    password: ${PG_PASSWORD:-password}
    driver-class-name: org.postgresql.Driver # optional
  jpa:
    hibernate:
      ddl-auto: create-drop # Use 'create-drop' for development, 'update' for production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
    enabled: false
  instance:
    hostname: customer


resilience4j:
  circuitbreaker:
    instances:
      fraudCheckService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      fraudCheckService:
        maxAttempts: 3
        waitDuration: 500ms