server:
  port: 8089
spring:
  application:
    name: transfer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/bank-realm

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true # Use IP address instead of hostname (resolves Api Gateway issues)