server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay    # проксируем Authorization header
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
        - id: front-ui
          uri: lb://FRONT-UI
          predicates:
            - Path=/main/**, /signup/**, /user/**, /css/**, /js/**   # все пути фронтенда
        - id: exchange
          uri: lb://EXCHANGE
          predicates:
            - Path=/api/rates/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/bank-realm


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true