server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
        - id: front-ui
          uri: lb://FRONT-UI
          predicates:
            - Path=/main/**, /signup/**, /user/**, /css/**, /js/**   # все пути фронтенда

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true