server:
  port: 8088
spring:
  application:
    name: cash
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.local:8090/realms/bank-realm
      client:
        registration:
          keycloak:
            client-id: cash
            client-secret: cash-secret
            authorization-grant-type: client_credentials
            scope: roles
        provider:
          keycloak:
            issuer-uri: http://keycloak.local:8090/realms/bank-realm

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: cash