server:
  port: 8085

spring:
  application:
    name: front-ui
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: front-ui
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8085/login/oauth2/code/{registrationId}"
            scope: openid,profile,roles
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/bank-realm
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/bank-realm

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

resilience4j:
  circuitbreaker:
    instances:
      customer-client:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      exchange-client:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      customer-client:
        maxAttempts: 3
        waitDuration: 500ms
      exchange-client:
        maxAttempts: 3
        waitDuration: 500ms
