server:
  port: 8085
  forward-headers-strategy: native # если приложение стоит за gateway и нужны корректные redirect-uri
spring:
  application:
    name: front-ui

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: front-ui
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/keycloak"
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: http://keycloak-bank:8080/realms/bank-realm

# ─── Keycloak admin-client (service account front-ui-admin) ──────────────────────
keycloak:
  admin:
    server-url:  http://keycloak-bank:8080
    realm:       bank-realm
    client-id:   front-ui-admin
    client-secret: front-ui-admin-secret


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    preferIpAddress: true

resilience4j:
  circuitbreaker:
    instances:
      customer-client:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      exchange-client:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      transfer-client:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      customer-client:
        maxAttempts: 3
        waitDuration: 500ms
      exchange-client:
        maxAttempts: 3
        waitDuration: 500ms
      transfer-client:
        maxAttempts: 3
        waitDuration: 500ms
