spring:
  datasource:
    password: ${PG_PASSWORD}
    url: jdbc:postgresql://postgres-bank:5432/notification
    username: ${PG_USER}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true