server:
  port: 8086
spring:
  application:
    name: exchange
  datasource:
    url: jdbc:postgresql://postgres-bank:5432/exchange
    username: amigoscode
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true # Use IP address instead of hostname (resolves Api Gateway issues)